services:
  downloader_bot:
    build: .
    container_name: downloader_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./downloads:/app/downloads
      - ./logs:/app/logs
      - ./data:/app/data
      - ./config:/app/config
      - ./cookies:/app/cookies
    user: "${USER_ID}:${GROUP_ID}"
