services:
  downloader_bot:
    build: .
    container_name: downloader_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./downloads:/app/downloads:z
      - ./logs:/app/logs:z
      - ./data:/app/data:z
      - ./config:/app/config:z
      - ./cookies:/app/cookies:z
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
